### ISSUE TITLE
docker compose crond container

### ISSUE THREAD

**Issue by antoniotvr** [fametec/glpi#19]
Hi.

Another thing to clarify.

In the crond section of yaml file you have indicated two times volumes:

 volumes:
          - glpi-volume:/usr/share/nginx/html/glpi:rw

 volumes: 
          - glpi-volume-files:/var/www/html/files:rw
          - glpi-volume-plugins:/var/www/html/plugins:rw

But why this?

I think that also in this case, like for php-fpm part, it depends if we will use apache or nginx.

Thank you

**Comment by eduardofraga** [comment]
1. nginx was removed
2. These files are persisted when update.
