### ISSUE TITLE
ERROR: Service 'glpi' depends on service 'php-fpm' which is undefined.

### ISSUE THREAD

**Issue by C138** [fametec/glpi#23]
Docker-compose v3.5

Server Ubuntu 20.05

` docker-compose build

ERROR: Service 'glpi' depends on service 'php-fpm' which is undefined.`

**Comment by jlgarnier** [comment]
Hi, the issue still pops up at the time of this post: was the docker-compose file properly fixed?
Thanks in advance for any help!
