### ISSUE TITLE
kubernetes and crond

### ISSUE THREAD

**Issue by StefanSa** [fametec/glpi#24]
Hi, @ricardo-f 
thanks for your good work here.
Question about kubernetes solution from you, can you please update, it so that this solution also work with crond.

Thank you for your time and effort.

**Comment by ricardo-f** [comment]
Hi @StefanSa can you elaborate it? Why do you need a crond? Maybe I'm out of context, from my point of view do you need to schedule something? If not, can you send any documentation about the crond of your point of view? So I can see if there is anyway to help.

**Comment by StefanSa** [comment]
As far as i know, Glpi needs Crond or croni. Similar to the Dockerimage, otherwise there are also problems with certain plugins such as fusioninventory

**Comment by ricardo-f** [comment]
Ok, got the idea, but unfortunately you can run cronjobs from inside a kubernetes deployments. However there is a kubernetes object called cronjob to do so, maybe you can schedule a cronjob get the data that you want and send it back to glpi, but this is a great "guess".

A doc about this:
https://opensource.com/article/20/11/kubernetes-jobs-cronjobs

**Comment by StefanSa** [comment]
Hi,

i already had this idea, here is a good example:

https://www.linkedin.com/pulse/creating-kubernetes-cron-job-backup-postgres-db-prakarsh-

**Comment by ricardo-f** [comment]
Ok, that doc is about the database backup, no problem to do that.
Where I've work we decide to go with other tool, so I don't have the experience with glpi, so I'm intrigued at the necessity of a cron for fusioninvetory? Can you send the commands that the cron would be executing in a "on-premises" instalation.

**Comment by ricardo-f** [comment]
#26 
Basic cronjob using the fametec/crond-glpi image was created with the purpose to give a lead, that cron can't be used in a prod env, going further in the discussion, I've recommend the usage of a DBaaS, like RDS or GCP Databases.

**Comment by eduardofraga** [comment]
CronJob

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by eduardofraga** [comment]
Created glpi-cronjob.yaml

**Comment by Asbest1337** [comment]
Hi, how to install Fussioninventory in this img?
