### ISSUE TITLE
"A link to the SQL server could not be established. Please check your configuration "

### ISSUE THREAD

**Issue by badisorfesprit** [fametec/glpi#28]
a question about kubernates yaml fil ! 
everything is working properly but it show on the browser 
"A link to the SQL server could not be established. Please check your configuration.

Le serveur Mysql est inaccessible. Vérifiez votre configuration."
any helps plz :)

**Comment by eduardofraga** [comment]
Wait for database populate.

**Comment by jlgarnier** [comment]
Hi, same issue on my fresh deployment: what does "Wait for database populate" mean? Does the database server have its own life in the background? 🤔 By the way, I've refreshed the page several times, waiting 5mn between each refresh, but to no avail...
Thanks in advance for any help!
