### ISSUE TITLE
no configure.sh in docker_glpi_1

### ISSUE THREAD

**Issue by realitear** [fametec/glpi#31]
D:\GLPI\glpi\docker>docker exec -it docker_glpi_1 /configure.sh
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/configure.sh": stat /configure.sh: no such file or directory: unknown

I tried to find the configure.sh from the vm but no lucky looking for it, is there any way to fix this? PLS

**Comment by eduardofraga** [comment]
Is deprecated and was removed.
